branches:
  only:
    - develop
    - master
    - /^release.*$/
language: objective-c
osx_image: xcode9.1
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
cache:
  - cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods
  - pod install --repo-update  --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/JJFloatingActionButton.xcworkspace -scheme JJFloatingActionButton-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.1' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
