branches:
  only:
    - develop
    - master
    - /^release.*$/
language: objective-c
osx_image: xcode9.1
cache:
  - cocoapods
  - bundler
podfile: Example/Podfile
xcode_workspace: Example/FloatingActionButton.xcworkspace
xcode_scheme: FloatingActionButton
xcode_sdk: iphonesimulator
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
install:
  - gem install cocoapods
  - pod install --repo-update --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/FloatingActionButton.xcworkspace -scheme FloatingActionButton -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
